baseURL = "https://sax.magaoidh.pro/"
languageCode = "en-gb"
title = "Streamer Alerts XPlat"
theme = "hugo-scroll"

[pagination]
  pagerSize = 5
enableRobotsTXT = true
copyright = "© 2025 Streamer Alerts"


[params]
  description = "Cross-platform live stream monitoring & alerts"
  favicon = "/favicon.ico"
  # hugo-scroll specific params (examples - adjust after theme fetch)
  author = "Streamer Alerts Team"
  customCSS = []

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
